server.port=8080
spring.application.name=CinemaTicketBookingErmurat
spring.mvc.charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
